version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - "127.0.0.1:8080:8080"
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    command:
      - -nginx.scrape-uri=http://127.0.0.1:8080/nginx_status
    depends_on: 
      - "nginx"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  helloworld:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 helloworld:app --reload --access-logfile -
    container_name: helloworld
    restart: unless-stopped
    expose:
      - 8080